[build-system]
requires = ["setuptools", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "pypolychord"
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest", "pytest-mpi"]

[tool.setuptools.dynamic]
version = {attr = "pypolychord.__version__"}
