name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, cmake-dev ]
# don't run the CRON part in my fork
#  schedule:
#    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  pip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies (Linux)
      run: sudo apt-get install gfortran libopenmpi-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mpi4py

    - name: Install pypolychord
      run: pip install -v .

    - name: Test pypolychord
      run: python run_pypolychord.py

    - name: Test pypolychord (MPI)
      run: mpirun -np 2 python run_pypolychord.py

  pip_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        cc: [gcc]
        python-version: [3.8]
    
    steps:
    - uses: actions/checkout@v2
    # - name: Set up Python ${{ matrix.python-version }}
      # uses: actions/setup-python@v2
      # with:
        # python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        brew install python cmake openmpi gcc
        echo which gfortran
        echo which gcc
        export FC=gfortran-11
        pip3 install --upgrade pip

    - name: Install pypolychord
      run: pip3 install -v .

    - name: Test pypolychord
      run: python3 run_pypolychord.py

    - name: Test pypolychord (MPI)
      run: mpirun -np 2 python3 run_pypolychord.py